base/urls.py

from django.urls import path

from base.client_views import singleClient
from base.upload_views import NotesPage, cancelService, confirmSerivce, editClient, editNote
from base.views import JismoniyPage, SMSPage, YaTTPage, YuridikPage, deleteClient, auctionPage, telegramPage, createClient, createService, deleteTask, editSMS, editService, finishTask, homePage, logoutPage, monitoringPage, serviceHistoryPage, tanirovkaPage, taskPage, teachersPage, uploadPage, deleteService, viewTaskPage, loginPage
from .user_views import CreateProfile, DeleteProfile, EditProfile, Profiles

urlpatterns = [
    path("login/", loginPage, name='login'),
    path("logout/", logoutPage, name='logout'),
    path("", homePage, name="home"),
    path("monitoring/", monitoringPage, name="monitoring"),
    path("upload/", uploadPage, name="upload"),
    path("create-service/", createService, name="create-service"),
    path("edit-service/<str:pk>", editService, name="edit-service"),
    path("delete-service/<str:pk>", deleteService, name="delete-service"),
    path("task/", taskPage, name="task"),
    path("view-task/<str:pk>", viewTaskPage, name="view-task"),
    path("delete-task/<str:pk>", deleteTask, name="delete-task"),
    path("finish-task/<str:pk>", finishTask, name="finish-task"),
    path("history/", serviceHistoryPage, name="history"),
    path("create-client/", createClient, name="create-client"),
    path("yatt/", YaTTPage, name='yatt'),
    path("jismoniy/", JismoniyPage, name='jismoniy'),
    path("yuridik/", YuridikPage, name='yuridik'),
    path("tanirovka/", tanirovkaPage, name='tanirovka'),
    path("auction/", auctionPage, name='auction'),
    path("teacher/", teachersPage, name='teacher'),


    path("cancel-serivce/<str:pk>", cancelService, name='cancel-service'),
    path("confirm-serivce/<str:pk>", confirmSerivce, name='confirm-service'),

    path("client/<str:pk>", singleClient, name='client'),
    path("edit-client/<str:pk>", editClient, name='edit-client'),

    path("notes/", NotesPage, name='notes'),
    path("note/<str:pk>", editNote, name='note'),
    path("sms/", SMSPage, name='sms'),
    path("edit-sms/<str:pk>", editSMS, name='edit-sms'),

    path("users/", Profiles, name="users"),
    path("create-user/", CreateProfile, name='create-user'),
    path("delete-user/<str:pk>", DeleteProfile, name="delete-profile"),
    path("edit-user/<str:pk>", EditProfile, name="edit-profile"),
    path("delete-client/<str:pk>", deleteClient, name="delete-client"),
    path("telegram/", telegramPage, name="telegram"),
]


control/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("base.urls")),
]

base/models.py

from http import client
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.db.models.signals import post_save
import datetime    
from datetime import date  

# Create your models here.
class Profile(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, null=True, blank=True)
    picture = models.ImageField(null=True, blank=True, default='static/profile/user-default.jpg', upload_to='static/profile/')
    phone = models.CharField(max_length=100, null=True, blank=True)
    ADMIN_CHOICES = (
        ('user', 'Oddiy foydalanuvchi'),
        ('superuser', 'Nazoratchi'),
        ('admin', 'Admin')
    )
    status = models.CharField(choices=ADMIN_CHOICES, max_length=200)
    OFFICE_CHOICES = (
        ('1', 'XXI ASR BUXGALTERIYA'),
        ('2', 'XXI ASR KOMPYUTER XIZMATLARI'),
        ('3', 'XXI ASR BUXGALTERIYA XIZMATLARI MARKAZI'),
    )
    office = models.CharField(choices=OFFICE_CHOICES, max_length=200)
    password = models.CharField(max_length=300)

    def __str__(self):
        return self.name    


class Access(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    user = models.ManyToManyField(Profile)
    name = models.CharField(max_length=255)

class Client(models.Model):
    picture = models.ImageField(null=True, blank=True, default="static/profile/user-default.jpg", upload_to="static/profile/")
    name = models.CharField(max_length=255)
    tin = models.CharField(max_length=255, null=True, blank=True)
    TYPE_CHOICES = (
        ('ytt','YaTT'),
        ('yuridik','Yuridik shaxs'),
        ('jismoniy','Jismoniy shaxs'),
        ('tanirovka','Tanirovka'),
        ('auction','Auksion'),
        ('teacher',"O'qituvchi"),
    )
    type = models.CharField(choices=TYPE_CHOICES, max_length=255)
    SUB_CHOICES = (
        ('aylanma', 'Aylanma'),
        ('oddiy', 'Oddiy'),
    )
    sub_type = models.CharField(choices=SUB_CHOICES, max_length=255, null=True, blank=True)
    gov_login = models.CharField(max_length=255, null=True, blank=True)
    gov_password = models.CharField(max_length=255, null=True, blank=True)
    jshshir = models.CharField(max_length=255, null=True, blank=True)
    guvohnoma_file = models.FileField(null=True, blank=True, upload_to="static/guvohnoma/")
    guvohnoma_exp = models.DateField(null=True, blank=True)
    director = models.CharField(max_length=255, null=True, blank=True)
    director_tin = models.CharField(max_length=255, null=True, blank=True)
    school = models.CharField(max_length=255, null=True, blank=True)
    work_as = models.CharField(max_length=255, null=True, blank=True)
    phone1 = models.CharField(max_length=255, null=True, blank=True)
    phone2 = models.CharField(max_length=255, null=True, blank=True)
    phone3 = models.CharField(max_length=255, null=True, blank=True)
    telegram = models.CharField(max_length=255, null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    key = models.FileField(upload_to='static/keys', null=True, blank=True)
    key_exp = models.DateField(null=True, blank=True)
    passport = models.FileField(null=True, blank=True, upload_to="static/passport/")
    owner = models.CharField(max_length=255, null=True, blank=True)
    tex_number = models.CharField(max_length=255, null=True, blank=True)
    text_series = models.CharField(max_length=255, null=True, blank=True)
    given_date = models.DateField(null=True, blank=True)
    expiry_date = models.DateField(null=True, blank=True)
    ustav = models.FileField(null=True, blank=True, upload_to="static/ustav/")
    selfy = models.FileField(null=True, blank=True, upload_to="static/selfy/")
    ruxsatnoma = models.FileField(null=True, blank=True, upload_to="static/ruxsatnoma/")
    texpas = models.FileField(null=True, blank=True, upload_to="static/texpas/")
    order1 = models.CharField(max_length=255, null=True, blank=True)
    order2 = models.CharField(max_length=255, null=True, blank=True)
    order3 = models.CharField(max_length=255, null=True, blank=True)
    auc_login = models.CharField(max_length=255, null=True, blank=True)
    auc_password = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def is_certificate_expired(self):
        if self.guvohnoma_exp:
            dates = datetime.datetime.strptime(str(self.guvohnoma_exp), "%Y-%m-%d").date()
            today = datetime.date.today()
            subs =  dates -today
            if subs.days >=1 and subs.days <=10:
                return 'in_ten_days'
            elif subs.days >10 and subs.days <=30:
                return 'in_a_month'
            elif subs.days > 30:
                return 'active'
            else:
                return 'inactive'
        else:
            return 'not_found'
    @property
    def is_key_expired(self):
        if self.key_exp:
            dates = datetime.datetime.strptime(str(self.key_exp), "%Y-%m-%d").date()
            today = datetime.date.today()
            subs =  dates -today
            if subs.days >=1 and subs.days <=10:
                return 'in_ten_days'
            elif subs.days >10 and subs.days <=30:
                return 'in_a_month'
            elif subs.days > 30:
                return 'active'
            else:
                return 'inactive'
        else:
            return 'not_found'

    @property
    def is_t_expired(self):
        if self.expiry_date:
            dates = datetime.datetime.strptime(str(self.expiry_date), "%Y-%m-%d").date()
            today = datetime.date.today()
            subs =  dates -today
            if subs.days >=1 and subs.days <=10:
                return 'in_ten_days'
            elif subs.days >10 and subs.days <=30:
                return 'in_a_month'
            elif subs.days > 30:
                return 'active'
            else:
                return 'inactive'
        else:
            return 'not_found'





class Service(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True,primary_key=True, editable=False)
    name = models.CharField(max_length=255)
    price = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Upload(models.Model):
    service = models.ForeignKey(Service, on_delete=models.PROTECT)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    reciever = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='reciever')
    STATUS_CHOICES = (
        ('0','Narxlanmagan'),
        ('5','Bajarilmagan'),
        ('10','Bajarilgan')
    )
    status = models.CharField(max_length=255, choices=STATUS_CHOICES, default='0')
    payment = models.CharField(max_length=255, null=True, blank=True)
    loaded_date = models.DateTimeField(auto_now_add=True)
    period = models.DateField(null=True, blank=True)
    uploaded_file = models.FileField(upload_to='static/files', null=True, blank=True)
    answer = models.TextField(max_length=350, null=True, blank=True)
    sender = models.ForeignKey(Profile, on_delete=models.PROTECT, related_name='sender')
    office = models.CharField(max_length=10)

    class Meta:
        ordering = ['-status', 'period']

class Task(models.Model):
    text = models.TextField(max_length=500)
    given_date = models.DateTimeField(auto_now_add=True)
    duration = models.DateField(null=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    sender = models.CharField(max_length=255, null=True, blank=True)
    STATUS_CHOICES = (
        ('0', 'Bajarilmagan'),
        ('5', 'Jarayonda'),
        ('10', 'Tugatilgan'),
    )
    client = models.ManyToManyField(Client, null=True, blank=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=255, default='0')
    given_file = models.FileField(upload_to='static/files/task', null=True, blank=True)
    answer_text = models.TextField(max_length=500, null=True, blank=True)
    answer_file = models.FileField(upload_to='static/files/task', null=True, blank=True)

    OFFICE_CHOICES = (
        ('1', 'XXI ASR BUXGALTERIYA'),
        ('2', 'XXI ASR KOMPYUTER XIZMATLARI'),
        ('3', 'XXI ASR BUXGALTERIYA XIZMATLARI MARKAZI'),
    )
    office = models.CharField(choices=OFFICE_CHOICES, max_length=200)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-given_date']

    @property
    def is_past_due(self):
            return date.today() >= self.duration


class SMS(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    text = models.TextField(null=True, blank=True)
    STATUS_CHOICES = (
        ('0', 'Raqam kiritilmagan'),
        ('5', 'Raqam xato kiritilgan'),
        ('10', 'Yuborilgan'),
    )
    status = models.CharField(choices=STATUS_CHOICES, max_length=200, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.client.name


class Notes(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    text = models.TextField(max_length=300)
    period = models.DateField(max_length=255)
    client = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True)
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, blank=True)
    payment = models.CharField(max_length=255, null=True, blank=True)
    payed = models.CharField(max_length=255, null=True, blank=True)

telegram/models.py
from django.db import models

# Create your models here.

telegram/views.py
from django.shortcuts import render

# Create your views here.

base/templates/base/cancel.html
{% extends 'main.html' %}
{% load static %}


{% block content %}
<div class="main-panel">
  
  {% if profile.status == 'admin' or profile.status == 'superuser'%}
  {% if obj %}
  <div class="content-wrapper">
    <div class="row">
      <div class="col-md-12 grid-margin">
        <div class="row">
          <div class="col-12 col-xl-8 mb-4 mb-xl-0">
            <h3 class="font-weight-bold">XXI ASR BUXGALTERIYA</h3>
            <h6 class="font-weight-normal mb-0">Xizmatni bekor qilish</span></h6>
          </div>
          <div class="col-12 col-xl-4">
           <div class="justify-content-end d-flex">
           
           </div>
          </div>
        </div>
      </div>
    </div>
 
    <div class="row">
      <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <p class="card-title">Xizmatni bekor qilish</p>
           <form action="" method="POST">
              {% csrf_token %}
             <p>
                 Siz <span class="text-danger">{{obj.service}}</span>ni o'chirmoqchimisiz ?
             </p>
             <a href="{% url 'home'%}">Ortga</a>
              <button class="btn btn-primary btn-rounded" type="submit">O'chirish</button>
            </form>
          </div>
        </div>
      </div>
     
    </div>

  </div>
  {% else %}

  <div class="content-wrapper">
    <div class="h1 text-danger text-center">
      Sahifa topilmadi
    </div>
  </div>

  {% endif %}
  {% else %}

  <div class="content-wrapper">
    <div class="h1 text-danger text-center">
      Sahifa topilmadi
    </div>
  </div>

  {% endif %}
 
</div>
{% endblock content %}

base/templates/base/confirm.html
{% extends 'main.html' %}
{% load static %}


{% block content %}
{% if profile.status == 'admin' or profile.status == 'superuser' %}
  {% if obj.status == '0' %}
  <div class="content-wrapper">
    <div class="row">
      <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <p class="card-title">Xizmatni narxlash</p>
          <form action="" method="POST">
              {% csrf_token %}
            <p>
                  {{obj.service}} - {{obj.client}}
            </p>
            <div class="form-group">
              <label for="">Summa</label>
              <input type="text" name="price" class="form-control">
            </div>
            <a href="{% url 'home'%}">Ortga</a>
              <button class="btn btn-primary btn-rounded" type="submit">Tasdiqlash</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% else %}
    {% if obj.reciever.user == request.user %}
    <div class="content-wrapper">
    <div class="row">
      <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <p class="card-title">Xizmatni tugatish</p>
          <form action="" method="POST">
              {% csrf_token %}
            <p>
                <b>Xizmatni yakunlash :</b>  {{obj.service}} - {{obj.client}}
            </p>
            <a href="{% url 'home'%}">Ortga</a>
              <button class="btn btn-primary btn-rounded" type="submit">Tasdiqlash</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    </div>
    {% else %}
    <div class="content-wrapper">
      <div class="h1 text-danger text-center">
        Sahifa topilmadi
      </div>
    </div>
    {% endif %}
  {% endif %}
{% elif profile.status == 'user' %}
{% if obj.status == '5' and obj.reciever.user == request.user %}
<div class="content-wrapper">
<div class="row">
  <div class="col-md-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <p class="card-title">Xizmatni tugatish</p>
      <form action="" method="POST">
          {% csrf_token %}
        <p>
            <b>Xizmatni yakunlash :</b>  {{obj.service}} - {{obj.client}}
        </p>
        <a href="{% url 'home'%}">Ortga</a>
          <button class="btn btn-primary btn-rounded" type="submit">Tasdiqlash</button>
        </form>
      </div>
    </div>
  </div>
</div>
</div>
{% else %}
<div class="content-wrapper">
  <div class="h1 text-danger text-center">
    Sahifa topilmadi
  </div>
</div>
{% endif %}
{% else %}
<div class="content-wrapper">
  <div class="h1 text-danger text-center">
    Sahifa topilmadi
  </div>
</div>
{% endif %}

{% endblock content %}

base/templates/base/createclient.html
{% extends 'main.html' %}
{% load static %}


{% block content %}
<div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      <div class="col-md-12 grid-margin">
        <div class="row">
          <div class="col-12 col-xl-8 mb-4 mb-xl-0">
            <h3 class="font-weight-bold">XXI ASR BUXGALTERIYA</h3>
            <h6 class="font-weight-normal mb-0">Mijozlarni ro'yxatga olish</span></h6>
          </div>
          <div class="col-12 col-xl-4">
           <div class="justify-content-end d-flex">
           
           </div>
          </div>
        </div>
      </div>
    </div>
 
    <div class="row">
      <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <p class="card-title">Mijoz kiritish</p>
           <form action="" method="GET">
           
              <b>Mijoz turini tanlang</b>
              <div class="form-group mt-3">
                <div class="form-check d-inline-block">
                  <label class="form-check-label">
                    <input type="radio" name="type" value="ytt" class="form-check-input">
                    YaTT
                  <i class="input-helper"></i></label>
                </div>
                <div class="form-check d-inline-block ml-2">
                  <label class="form-check-label">
                    <input type="radio" name="type" value="yuridik" class="form-check-input">
                    Yuridik
                  <i class="input-helper"></i></label>
                </div>
                <div class="form-check d-inline-block ml-2">
                  <label class="form-check-label">
                    <input type="radio" name="type" value="jismoniy" class="form-check-input">
                    Jismoniy
                  <i class="input-helper"></i></label>
                </div>
                <div class="form-check d-inline-block ml-2">
                  <label class="form-check-label">
                    <input type="radio" name="type" value="tanirovka" class="form-check-input">
                    Tanirovka
                  <i class="input-helper"></i></label>
                </div>
                <div class="form-check d-inline-block ml-2">
                  <label class="form-check-label">
                    <input type="radio" name="type" value="auction" class="form-check-input">
                    Auksion
                  <i class="input-helper"></i></label>
                </div>
                <div class="form-check d-inline-block">
                  <label class="form-check-label">
                    <input type="radio" name="type" value="teacher" class="form-check-input">
                    O'qituvchi
                  <i class="input-helper"></i></label>
                </div>
              </div>
              
              <button class="btn btn-rounded btn-primary " type="submit">Tasdiqlash</button>
              <a href="" class="btn">Ortga</a>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-6 grid-margin stretch-card">
          <div class="card">
              <div class="card-body">
                  <div class="card-title">Mijoz mavjudligini tekshirish</div>
                  <form method="get">
                      <input type="hidden" name="check">
                      <div class="row">
                          <div class="col-md-6">
                                <div class="form-group">
                                  <label>F.I.Sh</label>
                                  <input type="text" name="name" class="form-control form-control-sm">
                                </div>
                          </div>
                          <div class="col-md-6">
                                <div class="form-group">
                                  <label>JSHSHIR</label>
                                  <input type="text" name="j" class="form-control form-control-sm">
                                </div>
                          </div>
                          <div class="col-md-6">
                                <div class="form-group">
                                  <label>STIR</label>
                                  <input type="text" name="tin" class="form-control form-control-sm">
                                </div>
                          </div>
                      </div>
                      <button type="submit" class="btn btn-primary">Aniqlash</button>
                  </form>
              </div>
          </div>
      </div>
    </div>
    
    {% if checked %}
    <div class="row">
      <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
                <div class="card-title"><div class="float-left">Qidiruv natijalari</div>
                    <div class="float-right">
                        <button class="btn btn-sm btn-success" id="export_button">Excel</button>
                    </div>
                </div>
            
            <div class="table-responsive">
               <table class="table table-striped ytt" id="tasks">
                   <thead>
                       <tr>
                           <th>#</th>
                           <th>Mijoz</th>
                           <th>Turi</th>
                           <th>JSHSHIR</th>
                           <th>STIR</th>
                           <th>Telefon</th>
                           <th><i class="fa fa-cog"></i></th>
                       </tr>
                   </thead>
                   
                   <tbody>
                     {% for client in clients %}
                       <tr>
                           <td>{{ forloop.counter }}</td>
                           <td  style="display: flex; align-items: center ;">
                             {% if client.picture %}
                              <div class="profile-pics">
                                <img style="width: 100%; height: 100%; border-radius: 0; transition: all 1s;" src="/app{{client.picture.url}}" alt="">
                              </div>
                              <div class="img-text" style="line-height: 15px; padding-left: 15px;"><a href="{% url 'client' client.id %}">{{ client.name|wordwrap:"20"|linebreaksbr }}</a></div>
                              {% else %}

                                <div class="profile-pics">
                                  <img style="width: 100%; height: 100%; border-radius: 0; transition: all 1s;" src="{% static 'profile/profile-default.jpg' %}" alt="">
                                </div>
                                <div class="img-text" style="line-height: 15px; padding-left: 15px;"><a href="{% url 'client' client.id %}">{{ client.name|wordwrap:"20"|linebreaksbr }}</a></div>

                              {% endif %}

                             
                            </td>
                           <td>{{ client.get_type_display }}</td>
                           <td>{% if client.jshshir %} {{ client.jshshir|wordwrap:"14"|linebreaksbr }} {% else %} - {% endif %}</td>
                           <td>{% if client.tin %} {{ client.tin|wordwrap:"14"|linebreaksbr }} {% else %} - {% endif %}</td>
                           <td>{{ client.phone1 }}</td>
                            <td>
                              <a href="{% url 'edit-client' client.id %}"><i class="fa fa-pencil"></i></a>
                            </td>
                       </tr>
                       {% endfor %}

                   </tbody>
               </table>
           </div>
           
          </div>
        </div>
      </div>
     
    </div>
    {% endif %}

    {% if view %}
    <div class="row">
      <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <p class="card-title">Mijoz ma'lumotlari</p>
            
            <form action="" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group">
                  <label for="">{{field.label}}</label>
                  {{field}}
                </div>
              {% endfor %}
              <button type="submit" class="btn btn-rounded btn-primary">Kiritish</button>
            </form>
           
          </div>
        </div>
      </div>
     
    </div>
    {% endif %}

  </div>
 
</div>
{% endblock content %}

base/templates/base/profiles.html
{% extends 'main.html' %}
{% load static %}


{% block content %}
<div class="main-panel">
  <div class="content-wrapper">
    <div class="row">
      <div class="col-md-12 grid-margin">
        <div class="row">
          <div class="col-12 col-xl-8 mb-4 mb-xl-0">
            <h3 class="font-weight-bold">XXI ASR BUXGALTERIYA</h3>
            <h6 class="font-weight-normal mb-0">Xodimlar</span></h6>
          </div>
          <div class="col-12 col-xl-4">
           <div class="justify-content-end d-flex">
            <div class="dropdown flex-md-grow-1 flex-xl-grow-0">
              <a href="{% url 'create-user'%}">
                <button class="btn btn-sm btn-light bg-primary" type="button">
                  <i class="ti ti-plus font-weight-bold text-white"></i>
                </button>
              </a>
            </div>
           </div>
          </div>
        </div>
      </div>
    </div>
    
  
    <div class="row">
      <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            
          <div class="card-body">
            <p class="card-title">Xodimlar ro'yxati</p>
            <hr>
            <div class="table-responsive">
               <table class="table">
                   <thead>
                        <tr>
                            <th>#</th>
                            <th>Xodim</th>
                            <th>Login</th>
                            <th>Parol</th>
                            <th>Status</th>    
                            <th>Ofis</th>
                            <th></th>
                        </tr>
                   </thead>
                   <tbody>
                        {% for user in profiles %}
                          <tr>
                            <td>{{forloop.counter}}</td>
                            <td style="display: flex; align-items: center ;">
                              {% if user.picture %}
                                  <div class="profile-pics">
                                      <img style="width: 100%; height: 100%; border-radius: 0; transition: all 1s;" src="/app{{user.picture.url}}" alt="">
                                  </div>
                                  <div class="img-text" style="line-height: 15px; padding-left: 15px;">{{ user|wordwrap:"20"|linebreaksbr }}</div>
                                  {% else %}
                                  <div class="profile-pics">
                                      <img style="width: 100%; height: 100%; border-radius: 0; transition: all 1s;" src="{% static 'profile/profile-default.jpg' %}" alt="">
                                  </div>
                                  <div class="img-text" style="line-height: 15px; padding-left: 15px;">{{ user|wordwrap:"20"|linebreaksbr }}</div>
                              {% endif %}
                          </td>
                          <td>{{user.user}}</td>
                          <td>{{user.password}}</td>
                          <td>{{user.get_status_display}}</td>
                          <td>{{user.get_office_display}}</td>
                          <td>
                            {% if user.status != 'admin' %}
                            <a href="{% url 'delete-profile' user.id %}"><i class="fa fa-trash text-danger"></i></a>
                            <a href="{% url 'edit-profile' user.id %}"><i class="fa fa-pencil text-success"></i></a>
                            {% endif %}
                          </td>
                          </tr>
                        {% endfor %}
                   </tbody>
               </table>
           </div>
          {% if pagType %}
          <nav aria-label="Page navigation example">
            <ul class="pagination mt-3">
              {% if tasks.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{tasks.previous_page_number}}">&#10094 Oldingi</a></li>
              {% endif %}
              {% for page in page_range %}
              
              {% if page == tasks.number %}
              <li class="page-item active"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
              {% else %}
              <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
              {% endif %}
              {% endfor %}

              {% if tasks.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{tasks.next_page_number}}">Keyingi &#10095</a></li>
              {% endif %}

            </ul>
          </nav>
          {% endif %}
          </div>
        </div>
      </div>
     
    </div>

  </div>
 
</div>
{% endblock content %}